require 'active_support/inflector'
require 'db_connection'
require_relative '00_attr_accessor_object'
require_relative '01_sql_object'
require_relative '02_searchable'
require_relative '03_associatable'
require_relative '04_associatable2'
